apiVersion: v1
kind: Service
metadata:
  labels:
    app: talentplus-mongodb
  name: talentplus-mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: talentplus-mongodb
    